export const upcomingEvents = [
  {
    slug: 'new-member-open-house',
    title: '百团大战 · 新成员开放日',
    eyebrow: 'OPEN HOUSE',
    date: '9 月 2 日 · 09:00–20:00',
    year: '2026',
    place: '西交利物浦大学南校区 · 学术类社团区 8 号展位',
    type: '招新',
    status: 'upcoming',
    summary: '到 8 号展位认识 InfoCo、了解社团方向，与成员面对面交流，也可以参加现场“快问快答”挑战。',
    tone: 'orange',
    href: '/events/new-member-open-house',
  },
  {
    slug: 'all-members-meeting',
    title: '社员全员大会',
    eyebrow: 'ALL HANDS',
    date: '9 月 13 日 · 时间整理中',
    year: '2026',
    place: '地点整理中',
    type: '会议',
    status: 'upcoming',
    summary: 'Week 1 周末举行。具体时间、地点与会议安排整理中。',
    tone: 'violet',
    href: '/events#all-members-meeting',
  },
  {
    slug: 'python-programming-starter',
    title: 'Python 等编程入门课',
    eyebrow: 'CODING 101',
    date: '时间整理中',
    year: '2026',
    place: '地点整理中',
    type: '课程',
    status: 'upcoming',
    summary: '编程入门课程正在筹备，具体课程内容、时间与地点整理中。',
    tone: 'blue',
    href: '/events#python-programming-starter',
  },
  {
    slug: 'game-development-starter',
    title: '从零开始的游戏开发入门',
    eyebrow: 'GAME DEV 101',
    date: '时间整理中',
    year: '2026',
    place: '地点整理中',
    type: '课程',
    status: 'upcoming',
    summary: '游戏开发入门活动正在筹备，具体内容、时间与地点整理中。',
    tone: 'acid',
    href: '/events#game-development-starter',
  },
  {
    slug: 'club-culture-festival',
    title: '社团文化节',
    eyebrow: 'CLUB FESTIVAL',
    date: '时间整理中',
    year: '2026',
    place: '地点整理中',
    type: '文化节',
    status: 'upcoming',
    summary: '社团文化节活动正在筹备，具体形式、时间与地点整理中。',
    tone: 'orange',
    href: '/events#club-culture-festival',
  },
];
