export const upcomingEvents = [
  {
    slug: 'new-member-open-house',
    title: '百团大战 · 新成员开放日',
    eyebrow: 'OPEN HOUSE',
    date: '9 月 2 日 · 09:00–20:00',
    year: '2026',
    place: '西交利物浦大学南校区 · 学术类社团区 8 号展位',
    type: '招新',
    status: 'upcoming',
    summary: '介绍社团方向、项目与加入方式；现场开放“快问快答”。',
    tone: 'orange',
    href: '/events/new-member-open-house',
  },
  {
    slug: 'all-members-meeting',
    title: '社员全员大会',
    eyebrow: 'ALL HANDS',
    date: '9 月 13 日 · 时间待确认',
    year: '2026',
    place: '地点待确认',
    type: '会议',
    status: 'upcoming',
    summary: '认识团队，同步学期计划与部门分工。',
    tone: 'violet',
    href: '/events#all-members-meeting',
  },
  {
    slug: 'python-programming-starter',
    title: 'Python 等编程入门课',
    eyebrow: 'CODING 101',
    date: '时间待确认',
    year: '2026',
    place: '地点待确认',
    type: '课程',
    status: 'upcoming',
    summary: '通过基础练习掌握编程语法与问题拆解。',
    tone: 'blue',
    href: '/events#python-programming-starter',
  },
  {
    slug: 'game-development-starter',
    title: '从零开始的游戏开发入门',
    eyebrow: 'GAME DEV 101',
    date: '时间待确认',
    year: '2026',
    place: '地点待确认',
    type: '课程',
    status: 'upcoming',
    summary: '完成玩法设计、程序实现与可操作原型。',
    tone: 'acid',
    href: '/events#game-development-starter',
  },
  {
    slug: 'club-culture-festival',
    title: '社团文化节',
    eyebrow: 'CLUB FESTIVAL',
    date: '时间待确认',
    year: '2026',
    place: '地点待确认',
    type: '文化节',
    status: 'upcoming',
    summary: '展示社团项目，提供展览、互动挑战与小游戏。',
    tone: 'orange',
    href: '/events#club-culture-festival',
  },
];
