import type { Metadata } from 'next';
import { PageIntro, Shell } from '../components/SiteChrome';
import { projects } from '../content';

export const metadata: Metadata = { title: '项目与作品', description: '浏览 InfoCo 社员开发的游戏、网站、工具和创意项目。' };
const statuses = ['构思中', '开发中', '已发布', '已归档'];
const collaborationNotes = [['PICK A LANE', '选择方向', '可以从前端、游戏、视觉、文案或运营切入。'], ['JOIN A TEAM', '加入小组', '开放协作的项目会标记状态，方便找到入口。'], ['SHIP A TRACE', '留下成果', '可运行版本、复盘记录和展示材料都会沉淀到官网。']];
export default function ProjectsPage() {
  return <Shell><main id="top"><PageIntro index="03" label="PROJECTS / 项目与作品" title="有灵感，就去实现。" copy="收录在研、已发布及开放协作的项目。" accent="blue" /><section className="project-legend section-pad"><span>PROJECT STATUS</span><div>{statuses.map((status, index) => <span key={status}><i>0{index + 1}</i>{status}</span>)}</div></section><section className="field-board project-field-board section-pad"><div><span className="section-index light">BUILD WITH US / 协作方式</span><h2>不是等作品完成，<br />而是一起完成。</h2><p>项目页用于展示成果，也标出哪些方向正在找人。</p></div><div className="field-board-list">{collaborationNotes.map(([label, title, copy]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="project-index section-pad">{projects.map((project, index) => <article className={`project-row ${project.tone}`} key={project.slug}><div className="project-row-index">0{index + 1}</div><div className="project-row-visual"><span>{project.slug === 'infoco-exe' ? 'SIG' : project.slug === 'infoco-club' ? 'www' : 'G//P'}</span><i /></div><div className="project-row-copy"><div><span className="card-kicker">{project.kind}</span><span className={`status-tag status-${project.status}`}>{project.status}</span></div><h2>{project.name}</h2><p>{project.summary}</p><div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="project-row-side"><span>{project.collaborators ? '● OPEN FOR COLLABORATORS' : '○ TEAM COMPLETE'}</span>{project.href ? <a href={project.href}>查看项目 ↗︎</a> : <a href="/join">加入协作 ↗︎</a>}</div></article>)}</section><section className="submission-note"><span>BUILD WITH US</span><h2>项目开放协作</h2><p>程序、设计、叙事、运营均可参与；可提交选题或加入现有项目。</p><a className="btn btn-dark" href="/join">加入 InfoCo →</a></section></main></Shell>;
}
